-- IGDB integration fields on Game
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "igdbId" INTEGER;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "storyline" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "igdbUrl" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "totalRating" DOUBLE PRECISION;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "totalRatingCount" INTEGER;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "franchiseNames" TEXT[] DEFAULT '{}';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "dlcNames" TEXT[] DEFAULT '{}';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "similarGameNames" TEXT[] DEFAULT '{}';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "igdbHypes" INTEGER DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "igdbFollows" INTEGER DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "releaseStatus" TEXT DEFAULT 'RELEASED';

-- Unique index added separately so the migration stays idempotent
CREATE UNIQUE INDEX IF NOT EXISTS "Game_igdbId_key" ON "Game"("igdbId");
