-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "profileVisibility" TEXT DEFAULT 'PUBLIC';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinnedArticleId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isPublicBookmarks" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "followerCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "followingCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "points" INTEGER NOT NULL DEFAULT 0;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "User_pinnedArticleId_idx" ON "User"("pinnedArticleId");

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_pinnedArticleId_fkey" FOREIGN KEY ("pinnedArticleId") REFERENCES "Article"("id") ON DELETE SET NULL ON UPDATE CASCADE;
