-- IGDB full data fields on Game
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "igdbSlug" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "releaseStatus" TEXT DEFAULT 'Released';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "screenshotUrls" TEXT[] DEFAULT '{}';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "artworkUrls" TEXT[] DEFAULT '{}';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "allCompaniesJson" JSONB DEFAULT '[]';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "releaseDatesByPlatformJson" JSONB DEFAULT '[]';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "themes" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "keywords" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "gameModes" TEXT[] DEFAULT '{}';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "playerPerspectives" TEXT[] DEFAULT '{}';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "gameEngine" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "pegiRating" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "aggregatedRating" DOUBLE PRECISION;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "aggregatedRatingCount" INTEGER;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "igdbCommunityRating" DOUBLE PRECISION;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "igdbCommunityRatingCount" INTEGER;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "collectionName" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "dlcsJson" JSONB DEFAULT '[]';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "expansionsJson" JSONB DEFAULT '[]';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "similarGamesJson" JSONB DEFAULT '[]';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "videosJson" JSONB DEFAULT '[]';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "websitesJson" JSONB DEFAULT '{}';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "multiplayerModesJson" JSONB;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "languageSupportsJson" JSONB DEFAULT '[]';

-- "releaseStatus" already existed (RELEASED/UPCOMING) — switch to the new
-- title-case IGDB status vocabulary (Released/Alpha/Beta/Early Access/...)
ALTER TABLE "Game" ALTER COLUMN "releaseStatus" SET DEFAULT 'Released';
UPDATE "Game" SET "releaseStatus" = 'Released' WHERE "releaseStatus" IN ('RELEASED', 'UPCOMING') OR "releaseStatus" IS NULL;
